- name: Install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - nodejs

### 

- name: Create target dir 
  file: path={{server_tb_root}}
        owner=polyglot
        group=polyglot
        state=directory
        mode=0755

- current_git_sha: git_dir={{server_tb_root}}
  register: server_tb_root_git_sha

- name: Update server-tb
  sudo: True
  sudo_user: polyglot
  git:  repo=https://github.com/DrTom/cider-ci_server-tb.git
        dest={{server_tb_root}}
        version={{server_tb_sha}}
  register: update_server_tb
  when: '"{{server_tb_root_git_sha.value}}" != "{{server_tb_sha}}"'

- template: src=secrets.yml
            dest={{server_tb_root}}/config/secrets.yml

### 

- name: Create postgresql user
  postgresql_user:  name={{database.username}}
                    password={{database.password}}
                    role_attr_flags=CREATEDB,SUPERUSER
                    login_user=root
                    port={{database.port}}

- name: Create database
  postgresql_db:  name={{database.username}}
                  owner={{database.username}}
                  login_user=root
                  port={{database.port}}


- name: Configure database
  template: src=database.yml
            dest={{server_tb_root}}/config/database.yml
            owner=polyglot
            mode=0755
  register: configure_database

###

- name: Bundle
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
          && rbenv-load 
          && cd cider-ci_server-tb 
          && export RAILS_ENV={{rails_env}} 
          && export RBENV_VERSION={{item.version}} 
          && bundle install --deployment' polyglot
         executable=/bin/bash
  when: update_server_tb.changed and item.present
  with_items: ['{{rubies.jruby}}','{{rubies.mri}}']

- name: Migrate
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd cider-ci_server-tb 
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && bundle exec rake db:create db:migrate' polyglot
          executable=/bin/bash
  when: update_server_tb.changed

- name: Precompile assets 
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd cider-ci_server-tb 
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && export RAILS_RELATIVE_URL_ROOT={{web_sub_path}}
            && rm -rf public/assets/*"
            && rm -rf tmp/cache/*"
            && bundle exec rake assets:precompile' polyglot
          executable=/bin/bash
  when: update_server_tb.changed


### Seed and update configuration

- file: path={{repositories_path}}
        owner=polyglot
        group=polyglot
        state=directory
        mode=0755

- name: seedfile
  template: src=seeds.rb
             dest={{server_tb_root}}/db/seeds.rb
             owner=polyglot
  register: seedfile

- name: seed
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd cider-ci_server-tb 
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && export RAILS_RELATIVE_URL_ROOT={{web_sub_path}}
            && bundle exec rake db:seed' polyglot
          executable=/bin/bash
  register: server_configuration
  when: seedfile.changed

### 

- name: Create deployment descriptor
  template: src=deployment-descriptor.yml
            dest={{server_tb_descriptor_full_path}}
            owner=polyglot
            mode=755
  register: create_deployment_descriptor

- name: Deploy
  sudo: True
  sudo_user: polyglot
  command:  touch {{server_tb_descriptor_full_path}}.dodeploy
  when: update_server_tb.changed 
        or create_deployment_descriptor.changed 
        or configure_database.changed
        or server_configuration.changed


