- name: (Re)-Deploy Server TB
  command:  touch {{server_tb_descriptor_full_path}}.dodeploy
  sudo: True
  sudo_user: polyglot
  when: polyglot_force_restart

- name: (Re)-Deploy Server IM
  command:  touch {{server_im_descriptor_full_path}}.dodeploy
  sudo: True
  sudo_user: polyglot
  when: polyglot_force_restart

- name: Force logrotation
  shell: logrotate -f /etc/logrotate.d/polyglot-as
  when: polyglot_force_restart

- name: Restart polyglot-as
  service: name=polyglot-as state=restarted
  when: clone_polyglot_as.changed or copy_init_script.changed

- name: polyglot-as started
  service: name=polyglot-as 
           state=started


