
jboss_home: /opt/polyglot-as/server/jboss/
server_tb_descriptor_base_name: cider-ci_server-tb
server_tb_descriptor_full_path: "{{jboss_home}}/standalone/deployments/{{server_tb_descriptor_base_name}}_{{rails_env}}-knob.yml"

mri_ruby_version: 2.1.1
jruby_version: jruby-1.7.8
rubies: 
  - "{{mri_ruby_version}}"
  - "{{jruby_version}}"


