- name: Add the group "polyglot"
  group:  name=polyglot
          system=true

- name: Add the user "polyglot"
  user: name=polyglot
        generate_ssh_key=yes
        group=polyglot
        system=yes
        shell=/bin/bash

- name: Copy the init script
  template: src=polyglot-as.conf.init 
            dest=/etc/init/polyglot-as.conf 
  register: copy_init_script

- template: src=logrotate dest=/etc/logrotate.d/polyglot-as

- name: Make sure starting point is there
  file: path=/opt/polyglot-as
        owner=polyglot
        group=polyglot
        state=directory
        mode=0755

- current_git_sha: git_dir='/opt/polyglot-as'
  register: polyglot_as_current_git_sha

- service:  name=polyglot-as 
            state=stopped
  register: polyglot_as_stopped
  when: polyglot_force_restart
        or ('"{{polyglot_as_current_git_sha.value}}" != "{{polyglot_as_git_sha}}"')


- name: Forcefully kill process
  shell:  > 
          if pgrep -u polyglot -c; then
            echo "some polyglot processes are running, ... sending SIGTERM" 
            pkill -SIGTERM -u polyglot 
            sleep 10
            if pgrep -u polyglot -c; then
              echo "some polyglot processes are still running, ... sending SIGKILL" 
              pkill -SIGKILL -u polyglot 
              sleep 2
            fi
          fi
  when: polyglot_force_restart and polyglot_as_stopped.changed
        or ('"{{polyglot_as_current_git_sha.value}}" != "{{polyglot_as_git_sha}}"')


- name: clone polyglot-as
  sudo: True
  sudo_user: polyglot
  git:  repo=https://github.com/DrTom/polyglot-application-server.git 
        dest=/opt/polyglot-as
        version={{polyglot_as_git_sha}}
  register: clone_polyglot_as
  when: '"{{polyglot_as_current_git_sha.value}}" != "{{polyglot_as_git_sha}}"'



