- name: Create target dir 
  file: path={{server_im_root}}
        owner=polyglot
        group=polyglot
        state=directory
        mode=0755

- current_git_sha: git_dir={{server_im_root}}
  register: server_im_current_git_sha

- name: Update server-im
  sudo: True
  sudo_user: polyglot
  git:  repo=https://github.com/DrTom/cider-ci_server-im.git
        dest={{server_im_root}}
        version={{server_im_git_sha}}
  register: update_server_im
  when: '"{{server_im_current_git_sha.value}}" != "{{server_im_git_sha}"'



- name: Configure sever-im
  template: src=conf.yml
            dest={{server_im_root}}/conf.yml
            owner=polyglot
            mode=0755
  register: configure_server_im

- name: Update deployment descriptor
  template: src=deployment-descriptor.clj
            dest={{server_im_descriptor_full_path}}
            owner=polyglot
            mode=755
  register: update_deployment_server_im_descriptor_server_im


- name: Deploy
  sudo: True
  sudo_user: polyglot
  command:  touch {{server_im_descriptor_full_path}}.dodeploy
  when: update_server_im.changed
        or configure_server_im.changed
        or update_deployment_server_im_descriptor_server_im.changed
        or server_configuration.changed


