# {{ansible_managed}}
{{rails_env}}:
  adapter: postgresql
  database: {{database.database}}
  encoding: unicode
  port: {{database.port}}
  pool: {{database.tb_pool}}
  host: 127.0.0.1
  username: '{{database.username}}'
  password: '{{database.password}}'
