

- name: install jdk
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: 
    - firefox
    - fluxbox 
    - imagemagick
    - libimage-exiftool-perl
    - nodejs
    - tightvncserver
    - x11vnc 
